# Generated by Django 5.2.17 on 2026-09-27 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_employeeprofileeditrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "applicable_to",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular employees only"),
                            ("COSP", "COSP employees only"),
                            ("BOTH", "Both"),
                        ],
                        default="BOTH",
                        max_length=10,
                    ),
                ),
                (
                    "requires_full_routing",
                    models.BooleanField(
                        default=False,
                        help_text="True only for COSP Leave. Everything else is recorded by HR without Supervisor/AO/COH routing.",
                    ),
                ),
                (
                    "requires_justification",
                    models.BooleanField(
                        default=False,
                        help_text="True for Emergency Leave — must state why it's justified.",
                    ),
                ),
                (
                    "balance_tracking",
                    models.CharField(
                        choices=[
                            ("ACCRUED", "Monthly accrual"),
                            ("ANNUAL_CAP", "Fixed annual allotment"),
                            ("UNTRACKED", "Recorded, no system-enforced cap"),
                        ],
                        default="UNTRACKED",
                        max_length=15,
                    ),
                ),
                (
                    "monthly_accrual_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "annual_fixed_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "is_cumulative",
                    models.BooleanField(
                        default=True,
                        help_text="Only meaningful for ANNUAL_CAP: do unused days carry into next year?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "number_of_days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Working days covered. Entered directly (no holiday calendar yet), same as on the paper form.",
                        max_digits=5,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        help_text="Required for Emergency Leave; optional otherwise.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("RECOMMENDED_BY_AO", "Recommended by AO"),
                            ("APPROVED", "Approved"),
                            ("RECORDED", "Recorded"),
                            ("RETURNED", "Returned for correction"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SUBMITTED",
                        max_length=25,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApplicationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                (
                    "resulting_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("RECOMMENDED_BY_AO", "Recommended by AO"),
                            ("APPROVED", "Approved"),
                            ("RECORDED", "Recorded"),
                            ("RETURNED", "Returned for correction"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=25,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("acted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="leave.leaveapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["acted_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveCreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("EARNED", "Earned/granted"),
                            ("USED", "Used"),
                            ("ADJUSTMENT", "Manual adjustment"),
                            ("FORFEITED", "Forfeited"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive for a credit, negative for a deduction.",
                        max_digits=6,
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_credit_transactions",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="leave.leaveapplication",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-id"],
            },
        ),
    ]
