# Generated by Django 5.2.17 on 2026-09-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("leave", "0002_seed_leave_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavecredittransaction",
            name="attendance_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only for the auto-deduction CLAUDE.md §9 requires ('Undertime auto-deducts from leave credits') — confirmed 2026-09-27 that undertime charges against VL specifically.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="undertime_transactions",
                to="attendance.attendancerecord",
            ),
        ),
    ]
