"""
Django settings for bdh_hris project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! In production,
# set the BDH_HRIS_SECRET_KEY environment variable instead of editing this file.
SECRET_KEY = os.environ.get(
    "BDH_HRIS_SECRET_KEY",
    "django-insecure-=doqx446z^+=7x0)!*o00amg46b+n&cr%8udkzg*31d@9q=afp",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to OFF: a forgotten/missing BDH_HRIS_DEBUG must never leave debug
# pages (stack traces, settings, query details) exposed. For local
# development, opt in explicitly: BDH_HRIS_DEBUG=1 (e.g. in your own .env).
DEBUG = os.environ.get("BDH_HRIS_DEBUG", "0") == "1"

ALLOWED_HOSTS = os.environ.get("BDH_HRIS_ALLOWED_HOSTS", "*").split(",")

# Full path to LibreOffice's executable (soffice.exe on Windows), used to
# turn the filled CSC Form 6 / COSP Leave form into a PDF. Blank = look for
# it on PATH and in LibreOffice's usual install folders (see
# leave/pdf_convert.py). Set this only if it's installed somewhere unusual.
LIBREOFFICE_PATH = os.environ.get("BDH_HRIS_LIBREOFFICE_PATH", "")

# Only needed if the app is ever put behind a reverse proxy or reached by a
# hostname where the browser's Origin header wouldn't otherwise match
# ALLOWED_HOSTS (Django's CSRF check requires this since Django 4). Empty by
# default — plain HTTP, direct-to-Waitress, single-hostname deployments (the
# documented setup in DEPLOYMENT.md) don't need it set.
CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.environ.get("BDH_HRIS_CSRF_TRUSTED_ORIGINS", "").split(",") if origin
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "orgstructure",
    "accounts",
    "employees",
    "leave",
    "cto",
    "exchange",
    "attendance",
    "official_requests",
    "documents",
    "notifications",
    "dashboard",
    "auditlog",
]

# CLAUDE.md §13: RA 10173 personnel-record retention period, in years, for a
# SEPARATED employee (from Employee.separation_date). Kept configurable
# (env override) rather than hardcoded, per the same principle as CTO's
# multipliers (§7) — confirmed with the project owner as 10 years on
# 2026-09-27. See auditlog/retention.py.
RECORD_RETENTION_YEARS = int(os.environ.get("BDH_HRIS_RECORD_RETENTION_YEARS", "10"))

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves static files directly from Waitress in production (CLAUDE.md
    # §2) — no separate IIS/nginx. Harmless in dev too: before collectstatic
    # has ever run there's nothing in STATIC_ROOT, so it just falls through
    # and Django's own runserver static handling (DEBUG=True) takes over.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bdh_hris.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "notifications.context_processors.unread_notification_count",
                "dashboard.context_processors.dashboard_link",
                "auditlog.context_processors.audit_log_link",
                "employees.context_processors.nav_links",
            ],
        },
    },
]

WSGI_APPLICATION = "bdh_hris.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Production (on-prem Windows Server) uses PostgreSQL. Set BDH_HRIS_DB_NAME to
# switch to it; otherwise this falls back to SQLite for local development.

if os.environ.get("BDH_HRIS_DB_NAME"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["BDH_HRIS_DB_NAME"],
            "USER": os.environ.get("BDH_HRIS_DB_USER", "bdh_hris"),
            "PASSWORD": os.environ.get("BDH_HRIS_DB_PASSWORD", ""),
            "HOST": os.environ.get("BDH_HRIS_DB_HOST", "localhost"),
            "PORT": os.environ.get("BDH_HRIS_DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Where `manage.py collectstatic` gathers files for WhiteNoise to serve in
# production. Only used when DEBUG=False (see STORAGES below) — local dev
# and the test suite keep using Django's own static handling, unchanged.
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# CLAUDE.md §10: uploaded documents (medical certificates, government IDs,
# etc.) are confidential HR records — they must NEVER be served as plain
# static files. There is deliberately no MEDIA_URL/serve-media route in
# bdh_hris/urls.py: the only way to read a file is documents.views.
# document_download, which checks can_view_document() before opening it.
MEDIA_ROOT = os.environ.get("BDH_HRIS_MEDIA_ROOT", str(BASE_DIR / "secure_media"))

LOGIN_URL = "login"
# "Notifications" is deliberately the landing page: it's the one screen the
# sidebar shows to every role, Employee through System Administrator (see
# templates/base.html) — Dashboard and Audit Log are HR/AO/COH/SysAdmin-only
# (dashboard/permissions.py, auditlog/permissions.py) and would 403 for a
# plain Employee or Supervisor. The scaffold default of "/admin/" left every
# non-staff login landing on the bare Django admin, so this was changed as
# part of deployment prep — flagging it here since it changes what a person
# sees right after signing in, even though it touches no permission logic.
LOGIN_REDIRECT_URL = "notifications:notification_list"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
