# Generated by Django 5.2.17 on 2026-09-27 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgstructure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "name_extension",
                    models.CharField(
                        blank=True, help_text="Jr., Sr., III, etc.", max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex_at_birth",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                    ),
                ),
                (
                    "civil_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("WIDOWED", "Widowed"),
                            ("SEPARATED", "Separated"),
                            ("DIVORCED", "Divorced"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sss_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="SSS Number"
                    ),
                ),
                (
                    "pagibig_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Pag-IBIG Number"
                    ),
                ),
                (
                    "philhealth_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="PhilHealth Number"
                    ),
                ),
                (
                    "tin_number",
                    models.CharField(blank=True, max_length=20, verbose_name="TIN"),
                ),
                (
                    "gsis_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="GSIS Number"
                    ),
                ),
                ("residential_address", models.TextField(blank=True)),
                ("permanent_address", models.TextField(blank=True)),
                (
                    "telephone_mobile",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telephone/Mobile"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "employee_id",
                    models.CharField(
                        help_text="System Administrator only.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=150)),
                (
                    "item_plantilla_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Item/Plantilla No."
                    ),
                ),
                ("salary_grade", models.CharField(blank=True, max_length=10)),
                ("appointment_type", models.CharField(blank=True, max_length=100)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[("REGULAR", "Regular"), ("COSP", "COSP")],
                        default="REGULAR",
                        max_length=10,
                    ),
                ),
                ("date_of_appointment", models.DateField(blank=True, null=True)),
                ("date_hired", models.DateField(blank=True, null=True)),
                ("original_appointment_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="System Administrator only. Controls login/account status.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="An employee may be attached to more than one section (e.g. float staff).",
                        related_name="employees",
                        to="orgstructure.section",
                    ),
                ),
                (
                    "units",
                    models.ManyToManyField(
                        blank=True, related_name="employees", to="orgstructure.unit"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="System login account for this employee.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["surname", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EducationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education_level", models.CharField(max_length=100)),
                ("school", models.CharField(max_length=200)),
                ("degree_course", models.CharField(blank=True, max_length=200)),
                ("units_earned", models.CharField(blank=True, max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_history",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Education history",
                "ordering": ["employee", "id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeEditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("field_label", models.CharField(blank=True, max_length=150)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                (
                    "reason",
                    models.TextField(help_text="Required. Why this change was made."),
                ),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_edits_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employee edit history",
                "ordering": ["-edited_at", "field_name"],
            },
        ),
    ]
