# Generated by Django 5.2.17 on 2026-09-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employeeprofileeditrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="shift_hours",
            field=models.PositiveSmallIntegerField(
                choices=[(8, "8-hour shift"), (12, "12-hour shift")],
                default=8,
                help_text="Defines this employee's CTO 'day' length (a CTO day = one shift) and the half-day/full-day blocks their CTO can be used in. Added for the CTO engine (Phase 5) — confirmed 2026-09-27 that 8-hour and 12-hour shift staff need separate conversions.",
            ),
        ),
    ]
