# Generated by Django 5.2.17 on 2026-09-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_shift_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="separation_date",
            field=models.DateField(
                blank=True,
                help_text="System Administrator only. Date of resignation, retirement, termination, or death — anchors the personnel-record retention clock (CLAUDE.md §13 / auditlog app). Not set automatically when is_active is unticked, since the two can differ (e.g. a suspension) — the System Administrator enters the actual separation date on record.",
                null=True,
            ),
        ),
    ]
