# Generated by Django 5.2.17 on 2026-10-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employee_separation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Set when the account gets a temporary password (e.g. from the employee import). The person must choose a new password at their next login before using the system.",
            ),
        ),
    ]
