# Generated by Django 5.2.17 on 2026-10-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_must_change_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["surname", "first_name", "middle_name", "employee_id"]
            },
        ),
    ]
