# Generated by Django 5.2.17 on 2026-10-06 07:56

from django.db import migrations, models

# Existing free-text entries -> fixed levels. Checked in this order (most
# specific first). Anything that matches nothing is left as typed, and the
# dashboard counts it as "Not standardized" so HR can fix it.
KEYWORDS = [
    ("DOCTORATE", ("doctor", "phd", "ph.d", "ed.d", "edd", "dba")),
    ("MASTERS", ("master", "graduate stud", "post grad", "postgrad", "mba", "mpa", "msn")),
    ("VOCATIONAL", ("vocational", "trade", "tesda", "technical", "tech-voc", "techvoc")),
    ("COLLEGE", ("college", "bachelor", "tertiary", "undergrad", "baccalaureate", "university")),
    ("SECONDARY", ("secondary", "high school", "highschool", "senior high", "junior high", "shs", "jhs")),
    ("ELEMENTARY", ("elementary", "primary", "grade school")),
]


def standardize(apps, schema_editor):
    EducationHistory = apps.get_model("employees", "EducationHistory")
    for row in EducationHistory.objects.all():
        text = (row.education_level or "").strip().lower()
        for code, words in KEYWORDS:
            if text.upper() == code or any(w in text + " " for w in words):
                row.education_level = code
                row.save(update_fields=["education_level"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_employee_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="cosp_under",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PGP", "PGP (Provincial Government of Palawan)"),
                    ("LGU", "LGU (Local Government Unit)"),
                ],
                help_text="For COSP employees only: whether the contract is under the PGP or the LGU.",
                max_length=3,
                verbose_name="COSP under",
            ),
        ),
        migrations.AlterField(
            model_name="educationhistory",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("ELEMENTARY", "Elementary"),
                    ("SECONDARY", "Secondary"),
                    ("VOCATIONAL", "Vocational/Trade Course"),
                    ("COLLEGE", "College"),
                    ("MASTERS", "Graduate Studies - Master's"),
                    ("DOCTORATE", "Graduate Studies - Doctorate"),
                ],
                max_length=100,
            ),
        ),
        migrations.RunPython(standardize, migrations.RunPython.noop),
    ]
