# Generated by Django 5.2.17 on 2026-09-27 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0004_employee_separation_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionReviewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            (
                                "RETAIN",
                                "Retain — do not flag again until manually re-reviewed",
                            ),
                            (
                                "DISPOSE",
                                "Approved for disposal per records retention schedule",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Required. Basis for the decision."),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_reviews",
                        to="employees.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_reviews_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
    ]
