# Generated by Django 5.2.17 on 2026-09-27 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0003_employee_shift_hours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("OFFICIAL_BUSINESS", "Official Business"),
                            ("OFFICIAL_TIME", "Official Time"),
                            ("TRAVEL", "Travel"),
                            (
                                "OT_RESTDAY_HOLIDAY",
                                "Authorized OT / rest day / holiday work",
                            ),
                        ],
                        max_length=25,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "time_from",
                    models.TimeField(
                        blank=True,
                        help_text="Mainly for Official Time / a partial-day OT claim.",
                        null=True,
                    ),
                ),
                ("time_to", models.TimeField(blank=True, null=True)),
                (
                    "destination",
                    models.CharField(
                        blank=True, help_text="Mainly for Travel.", max_length=255
                    ),
                ),
                ("purpose", models.TextField()),
                (
                    "hours_requested",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hours worked — required for Authorized OT/restday/holiday work.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "is_restday_or_holiday",
                    models.BooleanField(
                        default=False,
                        help_text="OT/restday/holiday work only: whether this falls on a rest day or holiday.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("RECOMMENDED_BY_AO", "Recommended by AO"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SUBMITTED",
                        max_length=25,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_requests",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="OfficialRequestAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                (
                    "resulting_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("RECOMMENDED_BY_AO", "Recommended by AO"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=25,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("acted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="official_requests.officialrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["acted_at"],
            },
        ),
    ]
