# Generated by Django 5.2.17 on 2026-10-07 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("official_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="officialrequest",
            name="line_note",
            field=models.CharField(
                blank=True,
                help_text="Optional note for this line of a batch.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="OfficialRequestBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("OFFICIAL_BUSINESS", "Official Business"),
                            ("OFFICIAL_TIME", "Official Time"),
                            ("TRAVEL", "Travel"),
                            (
                                "OT_RESTDAY_HOLIDAY",
                                "Authorized OT / rest day / holiday work",
                            ),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "work_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OT", "Authorized overtime"),
                            ("REST_DAY", "Rest-day work"),
                            ("HOLIDAY", "Holiday work"),
                        ],
                        help_text="OT/rest-day/holiday batches only.",
                        max_length=10,
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        help_text="One shared purpose/reason for the whole batch."
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True, help_text="Travel only.", max_length=255
                    ),
                ),
                (
                    "filer_role",
                    models.CharField(
                        choices=[
                            ("SUPERVISOR", "Supervisor"),
                            ("HR_PROCESSOR", "HR Processor"),
                            ("HR_ADMINISTRATOR", "HR Administrator"),
                        ],
                        help_text="The role the batch was filed under; decides the route.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("RECOMMENDED_BY_AO", "Recommended by AO"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SUBMITTED",
                        max_length=25,
                    ),
                ),
                ("filed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "filed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-filed_at"],
            },
        ),
        migrations.AddField(
            model_name="officialrequest",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="official_requests.officialrequestbatch",
            ),
        ),
        migrations.CreateModel(
            name="OfficialRequestBatchAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                (
                    "resulting_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("RECOMMENDED_BY_AO", "Recommended by AO"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=25,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("acted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="official_requests.officialrequestbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["acted_at", "pk"],
            },
        ),
    ]
