# Generated by Django 5.2.17 on 2026-09-27 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0003_employee_shift_hours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CTOMultiplierRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_date", models.DateField(unique=True)),
                (
                    "weekday_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                (
                    "restday_holiday_multiplier",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="CTOCreditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(
                        help_text="The date the OT/rest-day/holiday work was performed."
                    ),
                ),
                ("hours_worked", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "is_restday_or_holiday",
                    models.BooleanField(
                        default=False,
                        help_text="Determines which multiplier applies (weekday vs rest day/holiday).",
                    ),
                ),
                (
                    "shift_hours_used",
                    models.PositiveSmallIntegerField(
                        help_text="Snapshot of the employee's shift_hours at entry time, so a later shift-length change never silently reinterprets this entry's day conversion."
                    ),
                ),
                (
                    "multiplier_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of the multiplier in effect on work_date — never recomputed later.",
                        max_digits=4,
                    ),
                ),
                ("credited_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("credited_days", models.DecimalField(decimal_places=2, max_digits=6)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cto_credit_entries",
                        to="employees.employee",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date"],
            },
        ),
        migrations.CreateModel(
            name="CTOUsageApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("number_of_days", models.DecimalField(decimal_places=2, max_digits=4)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("RECOMMENDED_BY_AO", "Recommended by AO"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SUBMITTED",
                        max_length=25,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cto_usage_applications",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="CTOCreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("EARNED", "Earned/credited"),
                            ("USED", "Used"),
                            ("ADJUSTMENT", "Manual adjustment"),
                            ("FORFEITED", "Forfeited"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive for a credit, negative for a deduction.",
                        max_digits=6,
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="cto.ctocreditentry",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cto_credit_transactions",
                        to="employees.employee",
                    ),
                ),
                (
                    "usage_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="cto.ctousageapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CTOUsageApplicationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                (
                    "resulting_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("RECOMMENDED_BY_AO", "Recommended by AO"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=25,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("acted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="cto.ctousageapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["acted_at"],
            },
        ),
    ]
