# Generated by Django 5.2.17 on 2026-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cto", "0002_seed_cto_multiplier_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctocreditentry",
            name="duty_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular OT/rest day/holiday duty"),
                    ("MEDICAL_TRANSPORT", "Medical Transport (Decking schedule)"),
                ],
                default="REGULAR",
                max_length=20,
            ),
        ),
    ]
