# Generated by Django 5.2.17 on 2026-09-28 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_entries_credited(apps, schema_editor):
    """Every entry recorded before claims existed was credited to the
    ledger the moment HR saved it, so it is CREDITED, not DRAFT. It had no
    OT request to link to, so it is recorded as an exception."""
    CTOCreditEntry = apps.get_model("cto", "CTOCreditEntry")
    for entry in CTOCreditEntry.objects.all():
        entry.status = "CREDITED"
        entry.credited_by_id = entry.recorded_by_id
        entry.credited_at = entry.recorded_at
        entry.exception_reason = "Recorded by HR direct entry, before CTO claims were linked to OT requests."
        entry.save(update_fields=["status", "credited_by", "credited_at", "exception_reason"])


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0003_ctocreditentry_duty_type'),
        ('employees', '0004_employee_separation_date'),
        ('official_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ctocreditentry',
            name='credited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctocreditentry',
            name='credited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ctocreditentry',
            name='exception_reason',
            field=models.TextField(blank=True, help_text='Required when there is no OT request (exception claim).'),
        ),
        migrations.AddField(
            model_name='ctocreditentry',
            name='ot_request',
            field=models.ForeignKey(blank=True, help_text='The approved OT/rest-day/holiday request this claim is filed from. Blank only for an HR Administrator exception claim.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cto_claims', to='official_requests.officialrequest'),
        ),
        migrations.AddField(
            model_name='ctocreditentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft — not yet credited'), ('CREDITED', 'Credited')], default='DRAFT', max_length=10),
        ),
        migrations.RunPython(mark_existing_entries_credited, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='ctocreditentry',
            constraint=models.UniqueConstraint(fields=('ot_request', 'work_date'), name='one_cto_claim_per_ot_workday'),
        ),
    ]
