# Generated by Django 5.2.17 on 2026-09-27 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0003_employee_shift_hours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyExchangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_a",
                    models.DateField(
                        help_text="Employee A's original assigned duty date."
                    ),
                ),
                (
                    "date_b",
                    models.DateField(
                        help_text="Employee B's original assigned duty date."
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "is_emergency",
                    models.BooleanField(
                        default=False,
                        help_text="Documented emergency (§8): allows same-day filing with written follow-up within 24 hours.",
                    ),
                ),
                (
                    "emergency_justification",
                    models.CharField(
                        blank=True,
                        help_text="Required when is_emergency is set — the documentation §8 requires.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CONSENT", "Pending consent from other employee"),
                            ("CONSENT_DECLINED", "Consent declined"),
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("RECOMMENDED_BY_AO", "Recommended by AO"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING_CONSENT",
                        max_length=25,
                    ),
                ),
                ("filed_at", models.DateTimeField(auto_now_add=True)),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_a",
                    models.ForeignKey(
                        help_text="The employee who initiates the request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_requests_initiated",
                        to="employees.employee",
                    ),
                ),
                (
                    "employee_b",
                    models.ForeignKey(
                        help_text="The employee Employee A proposes to exchange duty with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_requests_received",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-filed_at"],
            },
        ),
        migrations.CreateModel(
            name="DutyExchangeRequestAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                (
                    "resulting_status",
                    models.CharField(
                        choices=[
                            ("PENDING_CONSENT", "Pending consent from other employee"),
                            ("CONSENT_DECLINED", "Consent declined"),
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("RECOMMENDED_BY_AO", "Recommended by AO"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=25,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("acted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="exchange.dutyexchangerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["acted_at"],
            },
        ),
    ]
