# Generated by Django 5.2.17 on 2026-09-27 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("orgstructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("SUPERVISOR", "Supervisor"),
                            ("HR_PROCESSOR", "HR Processor"),
                            ("HR_ADMINISTRATOR", "HR Administrator"),
                            ("ADMINISTRATIVE_OFFICER", "Administrative Officer (AO)"),
                            ("CHIEF_OF_HOSPITAL", "Chief of Hospital (COH)"),
                            ("SYSTEM_ADMINISTRATOR", "System Administrator"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "is_oic",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is ad-hoc OIC (Officer-in-Charge) delegated authority, not a permanent assignment.",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for an ongoing/permanent assignment.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delegated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor who triggered this OIC delegation. Required when is_oic is True.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations_made",
                        to="employees.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="employees.employee",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="orgstructure.section",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="orgstructure.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["employee", "role"],
            },
        ),
    ]
