# Generated by Django 5.2.17 on 2026-10-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE", "Employee"),
                    ("SUPERVISOR", "Supervisor"),
                    ("HR_PROCESSOR", "HR Processor"),
                    ("HR_ADMINISTRATOR", "HR Administrator"),
                    ("ADMINISTRATIVE_OFFICER", "Administrative Officer (AO)"),
                    ("CHIEF_OF_HOSPITAL", "Chief of Hospital (COH)"),
                    ("SYSTEM_ADMINISTRATOR", "System Administrator"),
                    ("ICTU_STAFF", "ICTU Staff"),
                ],
                max_length=30,
            ),
        ),
    ]
