# Generated by Django 5.2.17 on 2026-09-27 12:04

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_type_value",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to apply to every instance of this model, or give the exact value of that model's own 'kind' field (e.g. MEDICAL_TRANSPORT, SL, TRAVEL) to narrow it.",
                        max_length=30,
                    ),
                ),
                (
                    "alternative_group",
                    models.CharField(
                        blank=True,
                        help_text="Requirements sharing the same non-blank group are alternatives to each other — uploading any ONE of them satisfies the whole group.",
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=False,
                        help_text="Medical certificates, government IDs, etc. — restricted per §10.",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["content_type", "sub_type_value", "label"],
            },
        ),
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        max_length=300, upload_to=documents.models.secure_upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="Bytes, captured at upload time."
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("JPG", "JPG/JPEG"), ("PNG", "PNG")],
                        max_length=5,
                    ),
                ),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=False,
                        help_text="Snapshotted from the requirement at upload time, or set directly for a supplementary confidential attachment.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False once superseded by a replacement — kept, not deleted, for the audit trail.",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which configured requirement this satisfies, if any (blank for a supplementary attachment).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploads",
                        to="documents.documentrequirement",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="documents.uploadeddocument",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedDocumentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("REPLACED", "Replaced an earlier document"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("acted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="documents.uploadeddocument",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only for a REPLACED event: the document this one superseded.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.uploadeddocument",
                    ),
                ),
            ],
            options={
                "ordering": ["acted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="documentrequirement",
            constraint=models.UniqueConstraint(
                fields=("content_type", "sub_type_value", "label"),
                name="unique_requirement_label_per_subtype",
            ),
        ),
    ]
