# Generated by Django 5.2.17 on 2026-10-09 04:36

import announcements.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgstructure", "0002_seed_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("OFFICE_ORDER", "Office Order"),
                            ("POLICY", "Policy"),
                            ("ACTIVITY", "Activity"),
                        ],
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Office Order No. 028 s. 2026"',
                        max_length=100,
                        verbose_name="Reference no.",
                    ),
                ),
                ("date_issued", models.DateField()),
                ("effective_date", models.DateField()),
                (
                    "summary",
                    models.TextField(
                        help_text="Short summary. The signed original remains the authority."
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional. After this date the announcement is archived automatically.",
                        null=True,
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        upload_to=announcements.models.announcement_pdf_path,
                        verbose_name="Signed copy (PDF)",
                    ),
                ),
                ("pdf_original_name", models.CharField(blank=True, max_length=255)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("ALL", "All staff"),
                            ("SELECTED", "Selected sections/units"),
                        ],
                        default="ALL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="orgstructure.section"
                    ),
                ),
                (
                    "units",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="orgstructure.unit"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_issued", "-published_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                (
                    "resulting_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("acted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="announcements.announcement",
                    ),
                ),
            ],
            options={
                "ordering": ["acted_at", "pk"],
            },
        ),
    ]
