# Generated by Django 5.2.17 on 2026-10-09 04:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0008_employee_archive"),
        ("exchange", "0001_initial"),
        ("orgstructure", "0002_seed_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="As written on the schedule, e.g. 7A-7P.",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=100)),
                ("start_time", models.TimeField(blank=True, null=True)),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Earlier than the start = ends the next day.",
                        null=True,
                    ),
                ),
                (
                    "paid_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=4
                    ),
                ),
                (
                    "is_duty",
                    models.BooleanField(
                        default=True, verbose_name="Counts as a duty day"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="DutySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted (for HR review)"),
                            ("REVIEWED", "Reviewed by HR"),
                            ("RECOMMENDED", "Recommended by AO"),
                            ("APPROVED", "Approved by COH"),
                            ("RECORDED", "Recorded by HR"),
                            ("RETURNED", "Returned"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                (
                    "preparer_role",
                    models.CharField(
                        choices=[("SUPERVISOR", "Supervisor"), ("HR", "HR")],
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="Lunch break hours 12:00NN-1:00PM",
                        verbose_name="Notes / remarks",
                    ),
                ),
                (
                    "cutoff_date",
                    models.DateField(
                        help_text="Exchange of Duty requests for this month, filed before the schedule is approved, must be filed at least 7 days before this date. Set by HR (default: the 20th of the month before)."
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duty_schedules",
                        to="orgstructure.section",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duty_schedules",
                        to="orgstructure.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                (
                    "resulting_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted (for HR review)"),
                            ("REVIEWED", "Reviewed by HR"),
                            ("RECOMMENDED", "Recommended by AO"),
                            ("APPROVED", "Approved by COH"),
                            ("RECORDED", "Recorded by HR"),
                            ("RETURNED", "Returned"),
                        ],
                        max_length=15,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("acted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="schedules.dutyschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["acted_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("old_shift", models.CharField(blank=True, max_length=10)),
                ("new_shift", models.CharField(blank=True, max_length=10)),
                ("reason", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="employees.employee",
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_changes",
                        to="exchange.dutyexchangerequest",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="schedules.dutyschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        help_text="Position at the time of the schedule.",
                        max_length=150,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_rows",
                        to="employees.employee",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="schedules.dutyschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "employee__surname", "employee__first_name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="schedules.schedulerow",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="schedules.shiftcode",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddConstraint(
            model_name="dutyschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unit__isnull", True)),
                fields=("section", "year", "month"),
                name="one_schedule_per_section_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="dutyschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unit__isnull", False)),
                fields=("unit", "year", "month"),
                name="one_schedule_per_unit_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulerow",
            constraint=models.UniqueConstraint(
                fields=("schedule", "employee"), name="one_row_per_employee"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulecell",
            constraint=models.UniqueConstraint(
                fields=("row", "date"), name="one_cell_per_row_day"
            ),
        ),
    ]
