# Generated by Django 5.2.17 on 2026-09-27 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0003_employee_shift_hours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricColumnMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "employee_id_column",
                    models.CharField(
                        default="Employee ID",
                        help_text="Column header holding the value that matches Employee.employee_id.",
                        max_length=100,
                    ),
                ),
                ("date_column", models.CharField(default="Date", max_length=100)),
                ("time_in_column", models.CharField(default="Time In", max_length=100)),
                (
                    "time_out_column",
                    models.CharField(default="Time Out", max_length=100),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="%Y-%m-%d",
                        help_text="Python strptime format.",
                        max_length=50,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="%H:%M:%S",
                        help_text="Python strptime format.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceCorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correction_type",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor administrative (HR-initiated)"),
                            ("FORMAL", "Formal (employee-initiated)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="The attendance date being corrected."),
                ),
                ("requested_time_in", models.TimeField(blank=True, null=True)),
                ("requested_time_out", models.TimeField(blank=True, null=True)),
                (
                    "requested_is_absent",
                    models.BooleanField(
                        default=False,
                        help_text="Check to correct this date to Absent instead of supplying times.",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SUBMITTED",
                        max_length=25,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_correction_requests",
                        to="employees.employee",
                    ),
                ),
                (
                    "filed_by",
                    models.ForeignKey(
                        help_text="Who filed this — the employee themselves for FORMAL, or the HR Processor/Administrator for MINOR.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceCorrectionRequestAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                (
                    "resulting_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                            ("PROCESSED_BY_HR", "Processed by HR"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=25,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("acted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="attendance.attendancecorrectionrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["acted_at"],
            },
        ),
        migrations.CreateModel(
            name="BiometricImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                (
                    "skipped_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Rows skipped because that employee/date was already manually corrected.",
                    ),
                ),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("error_log", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mapping_used",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="attendance.biometriccolumnmapping",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                (
                    "is_absent",
                    models.BooleanField(
                        default=False,
                        help_text="Only ever set by a manual/correction entry — a missing biometric punch on its own doesn't imply absence, since this system has no duty-schedule module to confirm the employee was expected to work that day.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("BIOMETRIC", "Biometric import"),
                            ("MANUAL", "Manually encoded/corrected"),
                        ],
                        default="BIOMETRIC",
                        max_length=10,
                    ),
                ),
                ("undertime_minutes", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="employees.employee",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="attendance.biometricimportbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "date"),
                        name="one_attendance_record_per_employee_per_day",
                    )
                ],
            },
        ),
    ]
