# Generated by Django 5.2.17 on 2026-10-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_seed_default_column_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="reason_category",
            field=models.CharField(
                choices=[
                    ("OFFLINE", "Offline"),
                    ("FAILED_ATTEMPT", "Failed Attempt"),
                    ("WRONG_ENTRY", "Wrong Button Selected / Invalid Entry"),
                    (
                        "ATTENDED_ACTIVITY",
                        "Attended meeting / activity / training / others (specify)",
                    ),
                    ("OTHERS", "Others (specify)"),
                ],
                default="OTHERS",
                help_text="As on the Missed Log Justification Form. Decides who validates (ICTU or HR).",
                max_length=20,
                verbose_name="Reason",
            ),
        ),
        migrations.AlterField(
            model_name="attendancecorrectionrequest",
            name="reason",
            field=models.CharField(
                blank=True,
                help_text="Required for 'Attended meeting/activity/training' and 'Others': say what it was.",
                max_length=255,
                verbose_name="Details",
            ),
        ),
        migrations.AlterField(
            model_name="attendancecorrectionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("VALIDATED", "Validated"),
                    ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                    ("PROCESSED_BY_HR", "Processed by HR"),
                    ("APPROVED", "Approved"),
                    ("RETURNED", "Returned"),
                    ("REJECTED", "Rejected"),
                ],
                default="SUBMITTED",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="attendancecorrectionrequestaction",
            name="resulting_status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("VALIDATED", "Validated"),
                    ("ENDORSED_BY_SUPERVISOR", "Endorsed by Supervisor"),
                    ("PROCESSED_BY_HR", "Processed by HR"),
                    ("APPROVED", "Approved"),
                    ("RETURNED", "Returned"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=25,
            ),
        ),
    ]
