# Generated by Django 5.2.17 on 2026-10-07 01:19

import django.db.models.deletion
from django.db import migrations, models


ICTU_REASONS = {"OFFLINE", "FAILED_ATTEMPT", "WRONG_ENTRY"}


def copy_to_lines(apps, schema_editor):
    """Each existing single-date request becomes a request with one line
    (Batch 2, Item 6). Nothing is lost: date, times, absent flag, reason
    category and details move onto the line."""
    Request = apps.get_model("attendance", "AttendanceCorrectionRequest")
    Line = apps.get_model("attendance", "AttendanceCorrectionLine")
    for r in Request.objects.all():
        formal = r.correction_type == "FORMAL"
        Line.objects.create(
            request=r, date=r.date, time_in=r.requested_time_in, time_out=r.requested_time_out,
            is_absent=r.requested_is_absent,
            overnight=bool(r.requested_time_in and r.requested_time_out and r.requested_time_out <= r.requested_time_in),
            reason_category=r.reason_category if formal else "", reason=r.reason or "",
        )
        if formal:
            r.validator = "ICTU" if r.reason_category in ICTU_REASONS else "HR"
            r.save(update_fields=["validator"])


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendancecorrectionrequest_reason_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="validator",
            field=models.CharField(
                blank=True,
                choices=[("ICTU", "ICTU Staff"), ("HR", "HR Staff")],
                help_text="FORMAL only: who validates, decided by the reasons on the lines (all lines in one request must belong to the same validator - owner decision 2026-10-07). Blank for MINOR.",
                max_length=5,
            ),
        ),
        migrations.CreateModel(
            name="AttendanceCorrectionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="The attendance date being corrected."),
                ),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                (
                    "overnight",
                    models.BooleanField(
                        default=False,
                        help_text="Shift ends the next day (time out earlier than time in).",
                    ),
                ),
                (
                    "is_absent",
                    models.BooleanField(
                        default=False,
                        help_text="Correct this date to Absent instead of supplying times.",
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OFFLINE", "Offline"),
                            ("FAILED_ATTEMPT", "Failed Attempt"),
                            ("WRONG_ENTRY", "Wrong Button Selected / Invalid Entry"),
                            (
                                "ATTENDED_ACTIVITY",
                                "Attended meeting / activity / training / others (specify)",
                            ),
                            ("OTHERS", "Others (specify)"),
                        ],
                        help_text="FORMAL: as on the Missed Log Justification Form. Blank for MINOR.",
                        max_length=20,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Details"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="attendance.attendancecorrectionrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request", "date"), name="unique_correction_line_date"
                    )
                ],
            },
        ),
        migrations.RunPython(copy_to_lines, migrations.RunPython.noop),
    ]
